services:
    nginx:
        volumes:
            - .:/app
        build:
            context: ./build/backend/nginx
        depends_on:
            - php
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - "8000:80"
        expose:
            - "80"
        networks:
            - backend
    php:
        volumes:
            - .:/app
        build:
            context: ./build/backend/php
        depends_on:
            - database
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        expose:
            - "9000"
        networks:
            - backend
            - database
    database:
        image: mysql:8.2
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: admin
            MYSQL_USER: admin
            MYSQL_DATABASE: main
        ports:
            - "3308:3306"
        expose:
            - "3306"
        networks:
            - database

networks:
    backend:
        driver: bridge
    database:
        driver: bridge
